cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/services'

brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'rbenv'
brew 'ruby-build'
brew 'wget'

cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
